service: gregschmit
image: ghcr.io/gregschmit/gregschmit.com
builder:
  arch: amd64

servers:
  web:
    - app1.schmit.net
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  host: gregschmit.com
  app_port: 8000

ssh:
  proxy: deploy@home.schmit.net

registry:
  server: ghcr.io
  username: gregschmit
  password:
    - GITHUB_TOKEN

env:
  clear:
    DJANGO_ENV: production
  secret:
    - PRODUCTION_KEY
