name: Pipeline
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - run: cat config/deploy.known_hosts >> ~/.ssh/known_hosts
      - uses: docker/setup-buildx-action@v3
      - uses: crazy-max/ghaction-github-runtime@v3
      - name: Build and deploy using Kamal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
        # We use `kamal setup` rather than `kamal deploy` so if we add or reprovision nodes, they
        # get configured and the env is always pushed/updated.
        run: bundle exec kamal setup
      - uses: snok/container-retention-policy@b95617ac96d929f7a37025691e1ad89be732fb46
        with:
          image-names: gregschmit.com
          cut-off: one hour ago UTC
          skip-tags: latest
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
